Vagrant.configure("2") do |config|

  config.vm.define "master", primary: true do |master|
    master.vm.box = "bento/ubuntu-20.04"
    master.vm.hostname = 'master'
    master.vm.network :private_network, ip: "192.168.56.100"

    master.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "master"]
      v.customize ["modifyvm", :id, "--memory", 512]
    end

    #master.vm.provision "shell", path: "ansible-setup-ubuntu.sh"
    master.vm.provision "shell" do |s|
      s.inline = <<-SHELL
        sudo apt -y install git
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install -y ansible
        cd /vagrant/ansible && ansible-galaxy role install -r requirements.yml -p ./roles/
      SHELL
    end
  end

  config.vm.define "submit" do |submit|
    submit.vm.box = "bento/ubuntu-20.04"
    submit.vm.hostname = 'submit'
    submit.vm.network :private_network, ip: "192.168.56.101"

    submit.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "submit"]
      v.customize ["modifyvm", :id, "--memory", 512]
    end
  end

  config.vm.define "compute" do |compute|
    compute.vm.box = "bento/ubuntu-20.04"
    compute.vm.hostname = 'compute'
    compute.vm.network :private_network, ip: "192.168.56.102"

    compute.vm.provider :virtualbox do |v2|
      v2.customize ["modifyvm", :id, "--name", "compute"]
      v2.customize ["modifyvm", :id, "--memory", 512]
    end
  end

end
