---

- name: Install slurm worker packages
  ansible.builtin.package:
    name: "{{ slurm_packages_worker }}"
    state: present
    cache_valid_time: 600

- name: Install cgroups if this is a worker host
  ansible.builtin.apt:
    name:
      - libcgroup1
      - cgroup-tools
    state: present
    cache_valid_time: 600

- name: Deploy /etc/slurm/cgroup.conf
  ansible.builtin.template:
    src: "{{ slurm_conf_cgroup_custom_template | default('cgroup.conf.j2') }}"
    dest: /etc/slurm/cgroup.conf
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: 0644
  when:
    - not slurm_config_git_repo is defined
    - not slurm_configless | bool
  notify: Restart slurm services

- name: Ensure the slurmd spool directory exists
  ansible.builtin.file:
    path: "{{ slurm_slurmd_spool_path | default('/var/spool/slurmd') }}"
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: 0755
    state: directory

- name: Deploy /etc/slurm/slurm.conf
  ansible.builtin.template:
    src: "{{ slurm_conf_custom_template | default('slurm.conf.j2') }}"
    dest: /etc/slurm/slurm.conf
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: 0644
  when:
    - not slurm_config_git_repo is defined
    - not slurm_configless
  notify: Restart slurm services

- name: Deploy the required configuration for slurm configless
  ansible.builtin.template:
    src: slurm_worker_configless.j2
    dest: /etc/default/slurmd
    owner: root
    group: root
    mode: 0644
  when: slurm_configless | bool
  notify: Restart slurm services

- name: Delete /etc/slurm and /etc/slurm-llnl when using slurm configless
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/slurm
    - /etc/slurm-llnl
  when: slurm_configless | bool

- name: Deploy /etc/systemd/system/slurmd.service.d/override.conf with our customizations
  block:

    - name: Create folder /etc/systemd/system/slurmd.service.d/
      ansible.builtin.file:
        path: /etc/systemd/system/slurmd.service.d/
        owner: root
        group: root
        state: directory
        mode: 0755

    - name: Deploy /etc/systemd/system/slurmd.service.d/override.conf
      ansible.builtin.copy:
        dest: /etc/systemd/system/slurmd.service.d/override.conf
        owner: root
        group: root
        mode: "0644"
        content: "{{ slurm_slurmd_systemd_override }}"

- name: Start and enable slurm worker daemon
  ansible.builtin.service:
    name: slurmd
    state: started
    enabled: true
