---

- name: Deploy /etc/slurm/slurm.conf
  ansible.builtin.template:
    src: "{{ slurm_conf_custom_template | default('slurm.conf.j2') }}"
    dest: /etc/slurm/slurm.conf
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: 0644
  when: not slurm_config_git_repo is defined
